import pandas as pd

series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])
print('Addition of two series is:')
print(series1 + series2)
print()
print('Subtraction of two series is:')
print(series1 - series2)
print()
print('Multiplication of two series is:')
print(series1 * series2)
print()
print('Division of two series is:')
print(series1 / series2)
